image: python:3.8-slim-buster

stages:
  - build
  - test

default:
  before_script:
    - apt-get update -qq && apt-get install -yqq curl make
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - source $HOME/.poetry/env
    - poetry install

build:
  stage: build
  script:
    - make build-prod

test:
  stage: test
  script:
    - make test
