image: python:3.7-slim-buster

stages:
  - build
  - test

default:
  before_script:
    - apt-get update -qq && apt-get install -yqq curl make nodejs npm
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - source $HOME/.poetry/env
    - npm --version
    - node --version
    - npm install -g npm
    - npm install cssnano-cli uglify-js html-minifier-cli --global
    - cd ./senceit-node
    - poetry install

build:node:
  stage: build
  script:
    - make build-prod

test:node:
  stage: test
  script:
    - make test
