version: "3"
services:
  node-red:
    build: .
    ports:
      - "3000:1880"
    volumes:
      - ./data:/data
    depends_on:
      - "mqtt"
  mqtt:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
